[package]
name = "forc-debug"
version.workspace = true
description = "Supports debugging Sway code via CLI and DAP server."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
dap.workspace = true
forc-pkg.workspace = true
forc-test.workspace = true
forc-tracing.workspace = true
fuel-core-client.workspace = true
fuel-types = { workspace = true, features = ["serde"] }
fuel-vm = { workspace = true, features = ["serde"] }
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
shellfish = { workspace = true, features = ["async", "rustyline", "tokio"] }
sway-core.workspace = true
sway-types.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
] }

[dev-dependencies]
dap = { version = "0.4.1-alpha1", features = ["client"] }
escargot = "0.5.7"
portpicker = "0.1.1"
rexpect = "0.4"
