[package]
name = "forc-debug"
version.workspace = true
description = "Supports debugging Sway code via CLI and DAP server."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
dap.workspace = true
dirs.workspace = true
forc-pkg.workspace = true
forc-test.workspace = true
forc-diagnostic.workspace = true
forc-util = { workspace = true, features = ["tx"] }
fuel-abi-types.workspace = true
fuel-core-client.workspace = true
fuel-tx.workspace = true
fuel-types = { workspace = true, features = ["serde"] }
fuel-vm = { workspace = true, features = ["serde"] }
rayon.workspace = true
rustyline.workspace = true
serde.workspace = true
serde_json.workspace = true
strsim.workspace = true
sway-core.workspace = true
sway-features.workspace = true
sway-types.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
] }
walkdir.workspace = true

[dev-dependencies]
dap = { version = "0.4.1-alpha1", features = ["client"] }
escargot.workspace = true
portpicker.workspace = true
rexpect.workspace = true

[lints]
workspace = true
