[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "script_transfer"

[constants]
OWNER_ADDRESS = { type = "b256", value = "0x8900c5bec4ca97d4febf9ceb4754a60d782abbf3cd815836c1872116f203f861" }

[dependencies]
interface = { path = "../interface" }
