[package]
name = "examples-checker"
description = "Runs `forc build` or `forc fmt --check` on Sway projects specified by paths or within Sway `examples` directory."
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.41"
clap = { version = "3.1", features = ["env", "derive"] }