[default]
extend-ignore-identifiers-re = [
    "var*",
    "ba",
    "Pn",
    "TRO",
    "tro",
    "Tro",
    "NOOP",
    "Nam",
    "typ",
    "ALOC",
    "Aloc",
    "aloc",
]

extend-ignore-re = [
    "(?Rm)^.*(#|//)\\s*typos:ignore$",
]

[files]
extend-exclude = [
    "docs/book/theme/highlight.js",
    "docs/reference/theme/highlight.js",
    "forc-plugins/forc-doc/src/static.files/highlight.js",
    "forc-pkg/src/source/reg/file_location.rs",
    "test/src/e2e_vm_tests/test_programs/should_fail/attributes_invalid_args/**",
    "test/src/e2e_vm_tests/test_programs/should_pass/language/attributes_unknown/**",
]
