[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "lib.sw"
license = "Apache-2.0"
name = "std"
version = "0.68.2"
description = "The standard library for the Sway programming language."
homepage = "https://github.com/FuelLabs/sway"
repository = "https://github.com/FuelLabs/sway"
documentation = "https://docs.fuel.network/docs/sway/"
organization = "FuelLabs"
categories = ["Algorithms", "Data structures", "Cryptography"]
keywords = ["library", "standard"]

[dependencies]
