[package]
name = "sway-ir-macros"
version.workspace = true
description = "Macros for sway's intermediate representation."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["derive", "extra-traits", "parsing"] }

[lints]
workspace = true
