[package]
name = "mdbook-forc-documenter"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "mdbook-forc-documenter"
path = "src/bin/mdbook-forc-documenter.rs"

[lib]
name = "mdbook_forc_documenter"
path = "src/lib.rs"


[dependencies]
anyhow = "1"
clap = { version = "3.1", features = [ "derive" ]  }
mdbook = { version = "0.4", default-features = false }
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
toml = "0.5"
