[package]
name = "mdbook-forc-documenter"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "mdbook_forc_documenter"
path = "src/lib.rs"

[[bin]]
name = "mdbook-forc-documenter"
path = "src/bin/mdbook-forc-documenter.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
mdbook.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
