[package]
name = "sway-types"
version = "0.39.1"
description = "Sway core types."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fuel-asm = { workspace = true }
fuel-crypto = { workspace = true }
fuel-tx = { workspace = true }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }

[features]
no-span-debug = []
