[package]
name = "sway-types"
version = "0.20.2"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "Sway core types."

[dependencies]
fuel-asm = "0.6"
fuel-crypto = "0.5"
fuel-tx = "0.13"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
