[package]
name = "sway-types"
version = "0.2.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2018"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "Sway core types."

[dependencies]
fuel-asm = "0.1"
fuel-tx = "0.1"
serde = { version = "1.0", features = ["derive"] }
