[package]
name = "sway-types"
version = "0.8.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "Sway core types."

[dependencies]
fuel-asm = "0.2"
fuel-crypto = "0.3"
fuel-tx = "0.6"
pest = { version = "3.0.4", package = "fuel-pest" }
pest_derive = { version = "3.0.4", package = "fuel-pest_derive" }
serde = { version = "1.0", features = ["derive"] }
