[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "array"

[dependencies]
core = { path = "../../sway-lib-core" }
std = { path = "../../sway-lib-std" }
