[project]
author = "Fuel Labs <contact@fuel.sh>"
entry = "main.sw"
license = "Apache-2.0"
name = "fizzbuzz"

[dependencies]
core = { git = "http://github.com/FuelLabs/sway-lib-core" }
std = { git = "http://github.com/FuelLabs/sway-lib-std" }
