# This workspace is a collection of packages that manages all the example contracts
# in the Sway repo, where each example is a package member of the workspace.
[workspace]
members = [
  # "abi_supertraits",
  "advanced_storage_variables",
  "arrays",
  "methods_and_associated_functions",
  "asm_return_tuple_pointer",
  "basic_storage_variables",
  "break_and_continue",
  "cei_analysis",
  "configurable_constants",
  "converting_types",
  "counter",
  "enums",
  "fizzbuzz",
  "hashing",
  "identity",
  "liquidity_pool",
  "match_expressions",
  "msg_sender",
  "native_asset",
  "nested_storage_variables",
  "option",
  "ownership",
  "ref_mut_params",
  "result",
  "signatures",
  "storage_example",
  "storage_map",
  "storage_vec",
  "struct_storage_variables",
  "structs",
  "time",
  "tuples",
  "type_aliases",
  "upgradeable_proxy/proxy",
  "upgradeable_proxy/implementation",
  "vec",
  "wallet_abi",
  "wallet_contract_caller_script",
  "wallet_smart_contract",
]
