[project]
name = "escrow"
version = "0.1.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
license = "Apache-2.0"

[workspace]

[dependencies]
fuel-gql-client = { version = "0.6", default-features = false }
fuel-tx = "0.9"
fuels = "0.13"
fuels-abigen-macro = "0.13"
tokio = { version = "1.12", features = ["rt", "macros"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
