[package]
name = "sway-server"
version = "0.1.6"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2018"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "LSP server for Sway."

[dependencies]
dashmap = "4.0.2"
lspower = "1.0.0"
pest = { version = "3.0", package = "fuel-pest" }
ropey = "1.2"
serde_json = "1.0.60"
sway-core = { version = "0.1.6", path = "../sway-core" }
sway-fmt = { version = "0.1.6", path = "../sway-fmt" }
sway-utils = { version = "0.1.6", path = "../sway-utils" }
tokio = { version = "1.3", features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
