[package]
name = "sway-server"
version = "0.1.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2018"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "LSP server for Sway."

[dependencies]
core-lang = { path = "../core-lang" }
dashmap = "4.0.2"
sway-fmt = { path = "../sway-fmt" }
lspower = "1.0.0"
fuel-pest = "3.0"
ropey = "1.2"
serde_json = "1.0.60"
sway-utils = { path = "../sway-utils" }
tokio = { version = "1.3", features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
