[package]
authors = ["leviathan88 <elvisdedic@outlook.com>"]
edition = "2018"
name = "sway-server"
version = "0.1.0"

[dependencies]
core_lang = {path = "../core_lang"}
dashmap = "4.0.2"
lspower = "1.0.0"
pest = "2.0"
ropey = "1.2"
serde_json = "1.0.60"
tokio = {version = "1.3", features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"]}

[profile.dev]
debug = 2
