[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "wallet_smart_contract"

[dependencies]
std = { path = "../../sway-lib-std" }
wallet_abi = { path = "../wallet_abi" }
