[package]
name = "sway-parse"
version.workspace = true
description = "Sway's parser"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
extension-trait.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
phf = { workspace = true, features = ["macros"] }
sway-ast.workspace = true
sway-error.workspace = true
sway-features.workspace = true
sway-types.workspace = true
thiserror.workspace = true
unicode-bidi.workspace = true
unicode-xid.workspace = true

[dev-dependencies]
assert_matches.workspace = true
insta = { workspace = true, features = ["ron"] }

[lints]
workspace = true
