[package]
name = "sway-parse"
version = "0.24.2"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "Sway's parser"

[dependencies]
extension-trait = "1.0.1"
num-bigint = "0.4.3"
num-traits = "0.2.14"
phf = { version = "0.10.1", features = ["macros"] }
sway-ast = { version = "0.24.2", path = "../sway-ast" }
sway-types = { version = "0.24.2", path = "../sway-types" }
thiserror = "1.0"
unicode-xid = "0.2.2"

[dev-dependencies]
assert_matches = "1.5.0"
