[package]
name = "test-macros"
version = "0.0.0"
description = "Macros for testing the Sway formatter."
publish = false
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
pastey.workspace = true
prettydiff.workspace = true

[package.metadata.cargo-udeps.ignore]
development = ["pastey", "prettydiff"]
