[package]
name = "forc-migrate"
version.workspace = true
description = "Migrate Sway projects to the next breaking change version of Sway."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
duplicate.workspace = true
forc-pkg.workspace = true
forc-tracing.workspace = true
forc-util.workspace = true
itertools.workspace = true
num-bigint.workspace = true
sha2.workspace = true
sway-ast.workspace = true
sway-core.workspace = true
sway-error.workspace = true
sway-features.workspace = true
sway-types.workspace = true
swayfmt.workspace = true

[lints]
workspace = true

