[package]
name = "forc-explore"
version = "0.26.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "A `forc` plugin for running the fuel block explorer."

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
dirs = "3.0.2"
forc-tracing = { version = "0.26.0", path = "../../forc-tracing" }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
tar = "0.4"
tokio = { version = "1.8", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
warp = "0.3"
