[package]
name = "sway-error"
version = "0.45.0"
description = "Sway's error handling"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
num-traits = "0.2.14"
smallvec = "1.7"
sway-types = { version = "0.45.0", path = "../sway-types" }
thiserror = "1.0"
uwuify = { version = "^0.2", optional = true }
either = "1.9.0"

[features]
default = []
uwu = ["uwuify"]
