[package]
name = "sway-error"
version = "0.30.1"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "Sway's error handling"

[dependencies]
extension-trait = "1.0.1"
num-bigint = "0.4.3"
num-traits = "0.2.14"
sway-ast = { version = "0.30.1", path = "../sway-ast" }
sway-types = { version = "0.30.1", path = "../sway-types" }
thiserror = "1.0"
