[package]
name = "swayfmt"
version = "0.46.1"
description = "Sway language formatter."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
forc-tracing = { version = "0.46.1", path = "../forc-tracing" }
ropey = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_ignored = "0.1.9"
sway-ast = { version = "0.46.1", path = "../sway-ast" }
sway-core = { version = "0.46.1", path = "../sway-core" }
sway-error = { version = "0.46.1", path = "../sway-error" }
sway-parse = { version = "0.46.1", path = "../sway-parse" }
sway-types = { version = "0.46.1", path = "../sway-types" }
sway-utils = { version = "0.46.1", path = "../sway-utils" }
thiserror = "1.0.30"
toml = { version = "0.7", features = ["parse"] }

[dev-dependencies]
paste = "1.0"
prettydiff = "0.6"
test-macros = { path = "test_macros" }
